title: Udesh Kumarasignhe's Stuff
email: mail@udesh.xyz
description: >-
  I'm Udesh Kumarasinghe, This is my personal blog where I write and post my ideas, opinions
  or any thing that comes to my mind. Most of the posts will be technical stuff but I try to
  keep an open mind. 
baseurl: "/stuff"
url: "stuff.udesh.xyz"
twitter_username: ThatUdeshUK
github_username:  UdeshUK

markdown: kramdown
plugins:
  - jekyll-feed
